<a href="https://colab.research.google.com/github/jlmunoz96/SIC2024/blob/main/SIC_Tarea_Clase_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##*Hacer ejemplos similares al título de Reshaping y números aleatorios explicando los resultados en un comentario o en markdown. Puede ser un ejemplo muy parecido, con otros números, pero con explicaciones propias de usted*

Reshaping es el cambio de forma de un array (o matriz) de los elementos internos que lo componen. Haciendo un "reshaping" podemos agregar, sustraer o modificar el número de elementos en cada dimensión.

Por ejemplo:

In [2]:
import pandas as pd
import numpy as np

In [6]:
#Generamos un array aleatorio (para este caso un array de una dimensión y que contenga 12 elementos que vayan del 0 al 11)
arr1 = np.random.randint(10, size=12)
arr1

array([4, 3, 9, 3, 3, 1, 3, 3, 7, 1, 6, 9])

In [7]:
#Al ser un arrange de 12 elementos, podemos modificar la matriz original de una dimensión a una de 2 dimensiones (ej: 4 arrays con 3 elementos)
arr1_ordenado = np.reshape(arr1, (4,3))
arr1_ordenado

array([[4, 3, 9],
       [3, 3, 1],
       [3, 3, 7],
       [1, 6, 9]])

In [8]:
#O podemos convertir ese mismo array de 1 dimensión a 3 dimensiones (donde 3 arrays tendran 2 arrays de 2 elementos cada uno)
arr1_3d = np.reshape(arr1, (3,2,2))
arr1_3d

array([[[4, 3],
        [9, 3]],

       [[3, 1],
        [3, 3]],

       [[7, 1],
        [6, 9]]])

Existe completa libertad para modificar la forma de un array siempre y cuando no transformemos un array a una forma que implique una mayor cantidad de elementos a los establecidos originalemente